# Generated by Django 5.0.4 on 2024-06-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_userfinanciallmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFinanciallModel',
            new_name='UserFinancialModel',
        ),
    ]
