# Generated by Django 5.0.4 on 2024-07-06 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_developerproject_no_assigned_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_group',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('estate_developers', 'Estate Developer'), ('gcb_admin', 'GCB Admin'), ('gcb_superadmin', 'GCB SuperAdmin'), ('software_engineer', 'Software Eng')], default='software_engineer'),
        ),
        migrations.AddField(
            model_name='property',
            name='notified_via_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Application Progress', 'Application Progress'), ('New Application', 'New Application'), ('General', 'General'), ('Payment Alert', 'Payment'), ('Property Warning', 'Warning')], default='General', max_length=21),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Property Description', null=True),
        ),
        migrations.CreateModel(
            name='AdminNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.BooleanField(default=False)),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.notification')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.BooleanField(default=False)),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.notification')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
