# Generated by Django 5.0.4 on 2024-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_remove_notification_user_notification_target_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Application Progress', 'Application Progress'), ('Application Approved', 'Application Approved'), ('Application Denied', 'Application Denied'), ('New Application', 'New Application'), ('General', 'General'), ('Payment Alert', 'Payment'), ('Property Warning', 'Warning')], default='General', max_length=21),
        ),
    ]
