# Generated by Django 5.0 on 2024-07-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_rename_read_status_adminnotifications_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerproject',
            name='no_assigned_units',
        ),
       
        migrations.AlterField(
            model_name='penalty',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='developer_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.developerproject'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rent_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rent_year',
            field=models.IntegerField(null=True),
        ),
        
    ]
