# Generated by Django 5.0 on 2024-07-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_rename_read_status_adminnotifications_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_number',
        ),
        migrations.AlterField(
            model_name='application',
            name='date_verification_completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_received',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
