# Generated by Django 5.0 on 2024-07-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_remove_application_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approval_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tenantinfo',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
