# Generated by Django 5.0.4 on 2024-07-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_remove_property_equity_ratio_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='year_of_first_project',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='developer',
            name='year_of_incorporation',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='developerproject',
            name='bedroom_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='developerproject',
            name='bedroom_size',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='developerproject',
            name='no_of_bedrooms',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='developerproject',
            name='project_no_of_units',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
