# Generated by Django 5.0.4 on 2024-07-08 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_alter_property_current_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='developer_project',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='coreapp.developerproject'),
        ),
    ]
