# Generated by Django 5.0.7 on 2024-08-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_alter_application_title'),
        ('coreapp', '0016_userfinancialmodel_start_date_and_more'),
    ]

    operations = [
    ]
