# Generated by Django 5.0.7 on 2024-08-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_merge_20240803_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='contact_person_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
