# Generated by Django 5.0 on 2024-07-27 02:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0019_merge_20240726_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Property Description', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='developer_project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coreapp.developerproject'),
        ),
        migrations.AlterField(
            model_name='propertypaymenttracker',
            name='last_paid_date_equity',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='propertypaymenttracker',
            name='last_paid_date_rent',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='propertypaymenttracker',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
