# Generated by Django 5.0 on 2024-07-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0020_alter_property_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('RESOLVED', 'Resolved')], max_length=25)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount', models.IntegerField(null=True)),
                ('completed', models.IntegerField(null=True)),
                ('date_resolved', models.DateField()),
                ('penalty_reason', models.TextField()),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPenaltyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_penalty_collection', models.JSONField(default=dict)),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.property')),
            ],
        ),
    ]
