# Generated by Django 5.0 on 2024-07-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0022_delete_propertypaymenttracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPaymentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('equity_progress', models.JSONField(default=dict)),
                ('rent_progress', models.JSONField(default=dict)),
                ('last_paid_date_rent', models.DateField(null=True)),
                ('last_paid_date_equity', models.DateField(null=True)),
                ('total_equity', models.FloatField(default=0)),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.property')),
            ],
        ),
    ]
