# Generated by Django 5.0 on 2024-07-28 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0024_remove_receipt_property_remove_receipt_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=255)),
                ('equity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=255)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=255)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=255)),
                ('payment_mode', models.CharField(default='Bank Transfer', max_length=100)),
                ('payment_date', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
