# Generated by Django 5.0.7 on 2024-08-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0027_merge_20240806_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerproject',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='property',
            name='developer_project',
        ),
        migrations.AddField(
            model_name='developerproject',
            name='developer',
            field=models.ManyToManyField(to='coreapp.developer'),
        ),
        migrations.AddField(
            model_name='property',
            name='developer_project',
            field=models.ManyToManyField(default=0, to='coreapp.developerproject'),
        ),
    ]
