# Generated by Django 5.0.7 on 2024-08-06 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0029_remove_developerproject_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerproject',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coreapp.developer'),
        ),
    ]
