# Generated by Django 5.0.7 on 2024-08-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0031_remove_property_developer_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerproject',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.developer'),
        ),
    ]
