# Generated by Django 5.0.7 on 2024-08-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0035_alter_property_developer_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='developer_project',
        ),
    ]
