# Generated by Django 5.0.4 on 2024-06-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinanciallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.FloatField()),
                ('target_rental_yield', models.FloatField()),
                ('init_down_payment', models.FloatField()),
                ('annual_rent_increase', models.FloatField()),
                ('annual_home_value_increase', models.FloatField()),
                ('years_to_pay_init_cost', models.FloatField()),
                ('per_unit_markup_cost', models.FloatField()),
                ('annual_equity_pymt_increase', models.FloatField()),
            ],
        ),
    ]
