# Generated by Django 5.0.4 on 2024-07-02 17:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_rename_userfinanciallmodel_userfinancialmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='business_email',
        ),
        migrations.RemoveField(
            model_name='property',
            name='business_phone',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contact_person_email',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contact_person_phone',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_ft',
        ),
        migrations.AddField(
            model_name='penalty',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penalty',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfinancialmodel',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.property'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rent_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rent_year',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('email_address', models.EmailField(max_length=150)),
                ('website', models.CharField(max_length=150, null=True)),
                ('year_of_incorporation', models.IntegerField(max_length=4)),
                ('year_of_first_project', models.IntegerField(max_length=4)),
                ('location_of_first_project', models.CharField(max_length=255, null=True)),
                ('key_contact_person', models.CharField(max_length=255, null=True)),
                ('contact_person_position', models.CharField(max_length=255, null=True)),
                ('contact_person_number', models.CharField(max_length=11, null=True)),
                ('contact_person_email', models.EmailField(max_length=150, null=True)),
            ],
            options={
                'unique_together': {('developer_name', 'location', 'email_address', 'year_of_incorporation')},
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='real_est_developer_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_est_developer', to='coreapp.developer'),
        ),
        migrations.CreateModel(
            name='DeveloperProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospective_project', models.BooleanField()),
                ('project_name', models.CharField(default='No Name Assigned', max_length=255, null=True)),
                ('project_start_date', models.DateField()),
                ('project_description', models.TextField(max_length=255)),
                ('project_no_of_units', models.IntegerField(max_length=4)),
                ('project_size', models.FloatField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House')], max_length=9)),
                ('no_of_bedrooms', models.IntegerField(max_length=5)),
                ('bedroom_size', models.IntegerField(max_length=2)),
                ('bedroom_price', models.IntegerField(max_length=12)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ROAD', 'Road'), ('WATER', 'Water'), ('SCHOOL', 'School'), ('HOSPITAL', 'Hospital'), ('ELECTRICITY', 'Electricity'), ('INTERNET_CABLE', 'Internet and Cable'), ('GAS_SUPPLY', 'Gas Supply'), ('SECURITY', 'Security'), ('PARKS_RECREATIONAL', 'Parks and Recreational Areas'), ('SWIMMING_POOL', 'Swimming Pool'), ('GYM_FITNESS', 'Gym and Fitness Centers'), ('PUBLIC_TRANSPORTATION', 'Public Transportation'), ('SHOPPING_CENTERS', 'Shopping Centers'), ('PARKING', 'Parking'), ('AIR_CONDITIONING_HEATING', 'Air Conditioning and Heating'), ('WASTE_DISPOSAL', 'Waste Disposal'), ('LAUNDRY_FACILITIES', 'Laundry Facilities'), ('GARDENS_LAWNS', 'Gardens and Lawns'), ('BALCONY_TERRACE', 'Balcony or Terrace'), ('PET_FRIENDLY', 'Pet-Friendly Areas'), ('ENTERTAINMENT_FACILITIES', 'Entertainment Facilities'), ('DINING_OPTIONS', 'Dining Options'), ('COMMUNITY_CENTERS', 'Community Centers'), ('LIBRARIES', 'Libraries'), ('SPORTS_FACILITIES', 'Sports Facilities'), ('PLAYGROUNDS', 'Playgrounds'), ('HEALTHCARE_FACILITIES', 'Healthcare Facilities'), ('CHILDCARE_SERVICES', 'Childcare Services'), ('EDUCATIONAL_INSTITUTIONS', 'Educational Institutions')], max_length=25), default=list, null=True, size=None)),
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.developer')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='developer_project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coreapp.developerproject'),
        ),
        migrations.CreateModel(
            name='PropertyPaymentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('paid_annual_rent', models.JSONField(default=dict)),
                ('earned_annual_equity', models.JSONField()),
                ('cum_equity_ratios', models.JSONField()),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.property')),
            ],
        ),
        migrations.DeleteModel(
            name='DeveloperInfo',
        ),
    ]
