# Generated by Django 5.0.4 on 2024-07-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_remove_penalty_date_remove_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerproject',
            name='no_assigned_units',
            field=models.IntegerField(default=0),
        ),
    ]
