# Generated by Django 5.0.4 on 2024-07-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminnotifications',
            old_name='read_status',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='tenantnotifications',
            old_name='read_status',
            new_name='is_read',
        ),
    ]
