# Generated by Django 5.0 on 2024-07-24 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_remove_developerproject_no_assigned_units_and_more'),
    ]

    operations = [
        
        # migrations.CreateModel(
        #     name='PropertyPenaltyTracker',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('late_penalty_collection', models.JSONField(default=dict)),
        #         ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.property')),
        #     ],
        # ),
        migrations.CreateModel(
            name='PropertyPaymentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_progress', models.JSONField(default=dict)),
                ('rent_progress', models.JSONField(default=dict)),
                ('total_equity', models.FloatField(default=0.0)),
                ('last_paid_date_rent', models.DateField(null=True, blank=True)),
                ('last_paid_date_equity', models.DateField(null=True, blank=True)),
                ('start_date', models.DateField(null=True, blank=True)),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.property')),
            ],
        ),
    ]
