# Generated by Django 5.0.4 on 2024-07-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_registrationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='equity_ratio_info',
        ),
        migrations.DeleteModel(
            name='EquityRatioInfo',
        ),
    ]
