# Generated by Django 5.0 on 2024-07-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_alter_application_approval_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
