# Generated by Django 5.0.4 on 2024-07-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_alter_developer_year_of_first_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='expected_rent_info',
        ),
        migrations.RemoveField(
            model_name='property',
            name='real_est_developer_info',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_type',
        ),
        migrations.DeleteModel(
            name='ExpectedRentInfo',
        ),
    ]
