# Generated by Django 5.0.4 on 2024-07-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_remove_property_expected_rent_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='current_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
