# Generated by Django 5.0.4 on 2024-07-17 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_alter_property_developer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinancialmodel',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
