# Generated by Django 5.0 on 2024-07-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_userfinancialmodel_start_date_and_more'),
    ]

    operations = [
    
        migrations.RemoveField(
            model_name='property',
            name='notified_via_email',
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Property Description', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='developer_project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coreapp.developerproject'),
        ),
        # migrations.DeleteModel(
        #     name='Penalty',
        # ),
        migrations.DeleteModel(
            name='PropertyPaymentTracker',
        ),
    ]
