# Generated by Django 5.0 on 2024-07-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_rename_paid_annual_rent_propertypaymenttracker_equity_progress_and_more'),
        ('coreapp', '0011_alter_application_title'),
        ('coreapp', '0018_remove_propertypaymenttracker_property_id_and_more'),
    ]

    operations = [
    ]
