# Generated by Django 5.0 on 2024-07-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_penalty_propertypenaltytracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyPaymentTracker',
        ),
    ]
