# Generated by Django 5.0 on 2024-07-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0023_propertypaymenttracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='property',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
