# Generated by Django 5.0 on 2024-07-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0025_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerproject',
            name='no_assigned_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='notified_via_email',
            field=models.BooleanField(default=False),
        ),
    ]
