# Generated by Django 5.0.7 on 2024-08-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_alter_developer_contact_person_number_and_more'),
        ('coreapp', '0026_developerproject_no_assigned_units_and_more'),
    ]

    operations = [
    ]
