# Generated by Django 5.0.7 on 2024-08-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0028_remove_developerproject_developer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerproject',
            name='developer',
        ),
        migrations.AddField(
            model_name='developerproject',
            name='developer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coreapp.developer'),
        ),
    ]
