# Generated by Django 5.0.7 on 2024-08-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0030_alter_developerproject_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='developer_project',
        ),
        migrations.AddField(
            model_name='property',
            name='developer_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coreapp.developerproject'),
        ),
    ]
