# Generated by Django 5.0.7 on 2024-08-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0033_alter_developerproject_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerproject',
            name='developer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='coreapp.developer'),
        ),
    ]
