# Generated by Django 5.0.7 on 2024-08-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0036_remove_property_developer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='developer_project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='coreapp.developerproject'),
        ),
    ]
